name: github pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  Deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.90.1'
          extended: true

      - name: Build
        run: |
          hugo --minify
          ls ./public

      - name: Clone isshe.github.io
        uses: actions/checkout@v2
        with:
          repository: isshe/isshe.github.io
          path: isshe.github.io
          token: ${{secrets.GITHUB_TOKEN}}

      - name: Deploy
        run: |
          rm -rf isshe.github.io/*
          cp -rf ./public/* isshe.github.io/
          cd isshe.github.io
          git config --local user.name "$username"
          git config --local user.email "$email"
          cat .git/config
          git add -A
          git commit -m "update site"
          git push origin master
          # https:://$username:$token@github.com/isshe/isshe.github.io.git
        env:
          token: ${{secrets.GITHUB_TOKEN}}
          username: isshe
          email: i.sshe@outlook.com
